# SPDX-License-Identifier: GPL-2.0

# required for overlay support
DTC_FLAGS_fsl-ls1028a-qds := -@
DTC_FLAGS_fsl-ls1028a-qds-13bb := -@
DTC_FLAGS_fsl-ls1028a-qds-65bb := -@
DTC_FLAGS_fsl-ls1028a-qds-7777 := -@
DTC_FLAGS_fsl-ls1028a-qds-85bb := -@
DTC_FLAGS_fsl-ls1028a-qds-899b := -@
DTC_FLAGS_fsl-ls1028a-qds-9999 := -@





dtb-$(CONFIG_ARCH_MXC) += imx8mq-evk.dtb imx8mq-evk-rpmsg.dtb imx8mq-evk-pcie1-m2.dtb imx8mq-evk-usd-wifi.dtb \
			  imx8mq-evk-usdhc2-m2.dtb imx8mq-evk-pcie-ep.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mq-evk-ak4497.dtb imx8mq-evk-audio-tdm.dtb imx8mq-evk-pdm.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mq-evk-root.dtb imx8mq-evk-inmate.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mq-evk-lcdif-rm67191.dtb imx8mq-evk-lcdif-adv7535.dtb imx8mq-evk-lcdif-mipi.dtb imx8mq-evk-lcdif-sn65dsi86.dtb imx8mq-evk-lcdif-tc358775.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mq-hummingboard-pulse.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mq-evk-dcss-rm67191.dtb imx8mq-evk-dcss-adv7535.dtb imx8mq-evk-dcss-mipi.dtb imx8mq-evk-dcss-tc358775.dtb imx8mq-evk-dcss-icn6201.dtb imx8mq-evk-dcss-sn65dsi86.dtb imx8mq-evk-dcss-i2c-sn65dsi86.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mq-evk-dual-display.dtb 
dtb-$(CONFIG_ARCH_MXC) += imx8mq-evk-hdmi-mipi.dtb 
dtb-$(CONFIG_ARCH_MXC) += imx8mq-librem5-devkit.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mq-nitrogen.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mq-pico-pi.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mq-evk-dp.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mq-zii-ultra-rmb3.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mq-zii-ultra-zest.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mq-ddr3l-val.dtb imx8mq-ddr4-val.dtb imx8mq-ddr4-val-gpmi-nand.dtb


dtb-$(CONFIG_ARCH_MXC) += imx8mq-ipc.dtb 
dtb-$(CONFIG_ARCH_MXC) += imx8mq-k37x.dtb 
dtb-$(CONFIG_ARCH_MXC) += imx8mq-k37x-dcss-tc358775.dtb imx8mq-k37x-dcss-sn65dsi86.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mq-k37x-lcdif-sn65dsi86.dtb imx8mq-k37x-lcdif-tc358775.dtb
